### ISSUE TITLE
Our to-do list

### ISSUE THREAD

**Issue by itchyshin** [itchyshin/mice_allometry#2]
- [x] @labw09 to keep writing 
- [x] @itchyshin - adding p values for SD difference between the sexes
- [x] @itchyshin - adding meta-analysis
- [x] @itchyshin - merging p values
- [x] @itchyshin - doing a new fig 2 (scenarios)
- [x] @itchyshin - doing fig 3 (meta-analysis)
- [x] @itchyshin - doing fig 4 (regression & correlations among differences between a, b and SD
- [x] @itchyshin - fixing figures (esp - fig 2 - some numbers are wrong)
- [x] @mlagisz - doing Rmd to tidy up
- [x] @mlagisz - tidy up all figs
- [x] @itchyshin will need to add to the method section
